### ISSUE TITLE
List with skill-categories required 

### ISSUE THREAD

**Issue by korma0815** [charichu/saon#48]
Currently, all headlines between the skills are hardcoded like 'between skill 13 and 14, make subheadline "Physical Skills"'

For later multilanguage support, i require a list that changes dynamically with the current language

e.g.

skillCategories:

- Physical Skills
- Social Skills 
- Nature Skills 
- Knowledge Skills 
- Craft Skills

**Comment by charichu** [comment]
Added, but is the only multilanguage part for now. Will add more later on if needed.

**Comment by charichu** [comment]
![image](https://user-images.githubusercontent.com/32455463/101269688-c0c68580-3771-11eb-84ce-460c513c7f42.png)
