### ISSUE TITLE
Skills missing checks

### ISSUE THREAD

**Issue by korma0815** [charichu/saon#49]
Some skills like 

- Klettern, 
- Kraftakt
- Reiten
- Schwimmen
- Zechen
- Fesseln
- Bergbau
- Metallbearbeitung

are missing check2 and/or check3

![chrome_dWsTTD87KG](https://user-images.githubusercontent.com/37847187/100595797-afa5f080-32fb-11eb-9e53-6f5d275b1b6f.png)

**Comment by korma0815** [comment]
There are more than the ones listed, these are just the ones i found

**Comment by charichu** [comment]
Forgot to reduce the index, so all checks shifted +1, which meant some were undefined and ALL were wrongly mapped

![image](https://user-images.githubusercontent.com/32455463/101270065-852dba80-3775-11eb-975b-b053c682df8f.png)
