### ISSUE TITLE
Weapon damage is not calculated correctly for some weapons

### ISSUE THREAD

**Issue by korma0815** [charichu/saon#50]
![image](https://user-images.githubusercontent.com/37847187/100603396-5347ce80-3305-11eb-9e6b-3bfd4ab406d2.png)

"Dolch" should be 1W6+4 in this case.
Brecheisen 1W6+4

Character sheet:
![image](https://user-images.githubusercontent.com/37847187/100603328-301d1f00-3305-11eb-9ddf-e9ff1df784e8.png)

**Comment by korma0815** [comment]
[edrik.zip](https://github.com/charichu/saon/files/5615593/edrik.zip)
here's the char

**Comment by charichu** [comment]
@korma0815 
CAREFUL  POTENTIAL BREAKING CHANGE:
I added a damageNew, with a different output, which looks cleaner i think and should be quicker to use.
See picture below. Let me know, when I can remove the old fields bonusDamage and damage (no hurry)
![image](https://user-images.githubusercontent.com/32455463/101269650-6f1dfb00-3771-11eb-8720-ee3876147b31.png)
