### ISSUE TITLE
Disadvantages custom input text missing

### ISSUE THREAD

**Issue by korma0815** [charichu/saon#51]
Some disadvantages like "Personality Flaw" require a custom input, these don't show up currently

Example DISADV_33, see this character
[edrik.zip](https://github.com/charichu/saon/files/5621498/edrik.zip)

**Comment by charichu** [comment]
Appears now as "text" as well: 
![image](https://user-images.githubusercontent.com/32455463/101270360-798fc300-3778-11eb-942f-0b239eba11f1.png)
