### ISSUE TITLE
DSA 4 to 5 changes missing

### ISSUE THREAD

**Issue by korma0815** [charichu/saon#61]
The talent name changes from version 4 to 5 are not yet included 

- Diskus → Diskusse
- Spiesswaffen → Spießwaffen
- Gaukelei → Gaukeleien
- Sinnenschärfe → Sinnesschärfe
- Bekehren → Bekehren & Überzeugen
- Sich verkleiden → Verkleiden
- Angeln/Fischen → Fischen & Angeln
- Brettspiel/Glücksspiel → Brett und Glücksspiel
- Religion → Götter & Kulte
- Sagen und Legenden → Sagen und Legenden
- Spherenkunde → Sphärenkunde
- Sternenkunde → Sternkunde
- Alchemie → Alchimie
- Segeln → Boote & Schiffe
- Fahrzeuge lenken → Fahrzeuge
- Malen/Zeichnen → Malen & Zeichnen
- Schlösser knacken → Schlösserknacken
- Bergbau → Steinbearbeitung
- Stofbearbeitung → Stoffbearbeitung

Combat technique "Peitschen" is missing

**Comment by charichu** [comment]
> Combat technique "Peitschen" is missing

Added, the id CT_( was not appearing in the original Ids-file I used to map the combatSkills.

Prepared a little bit to make the skill names multilanguage as well.
